Update hscs launch plans with technical topics, day in the life, courses and books
DPI-WE/curriculum pull request #53
Opened 2024-07-08 23:45 UTC by thierrychau

…courses

2024-07-10 15:36 UTC, heratyian requested changes

2024-07-10 15:36 UTC, heratyian commented on cohorts/we-2024-7-1-sdf-bridge/launch-plans.md
> +- [Patterns of Enterprise Application Architecture](https://martinfowler.com/books/eaa.html)
I swapped this out with the spring book. Can you update?

2024-07-10 15:36 UTC, heratyian commented on cohorts/we-2024-7-1-sdf-bridge/launch-plans.md
>  - [Hyperskill: Java Backend Developer (Spring Boot)](./java.md#hyperskill-java-backend-developer-spring-boot)
I added learncs.online as another good free java resource. Good to add especially with hyperskill free tier limits.

2024-07-12 21:02 UTC, thierrychau commented on cohorts/we-2024-7-1-sdf-bridge/launch-plans.md
>  - [Hyperskill: Java Backend Developer (Spring Boot)](./java.md#hyperskill-java-backend-developer-spring-boot)
Updated

2024-07-12 21:02 UTC, thierrychau commented on cohorts/we-2024-7-1-sdf-bridge/launch-plans.md
> +- [Patterns of Enterprise Application Architecture](https://martinfowler.com/books/eaa.html)
Updated

2024-07-26 16:30 UTC, heratyian approved these changes
Looks great. Go ahead and update canvas.

2024-07-26 20:48 UTC, merged